#this file contains output functions to generate .nec file for nec2c
#here must be more useful functions/classes to use file/stdout


def CM_block (line):
    """returns whole CM block with end of comments"""
    outline='CM ---NEC file, automaticaly generated by antenna-generator--- \n'
    outline+='CM'+line
    outline+='CE ---End of comments section--- \n\n\n'
    return outline

def GW_line (tag, segs, start[], end[], radius):
    """returns GW (wire) line"""
    return f'GW {tag:3} {segs:3} {start[0]:5} {start[1]:5} {start[2]:5} \
        {end[0]:5} {end[1]:5} {end[2]:5} {radius} \n'

def GE_line (gnd):
    """returns GE (geometry end and ground options)
    
    gnd     0 - free space, no ground
            1 - ground and reflection
           -1 - ground, without reflection

    """
    return f'GE {gnd} 0 0 0 0 0 0 0 0\n\n\n'
