#this file contains output functions to generate .nec file for nec2c
#here must be more useful functions/classes to use file/stdout

#returns whole CM block with end of comments
def CM_block (line):
    outline='CM ---NEC file, automaticaly generated by antenna-generator--- \n'
    outline+='CM'+line
    outline+='CE ---End of comments section--- \n\n\n'
    return outline

#returns GW (wire) line
def GW_line (tag, segs, start[], end[], radius):
    return f'GW {tag:3} {segs:3} {start[0]:5} {start[1]:5} {start[2]:5} \
        {end[0]:5} {end[1]:5} {end[2]:5} {radius} \n'

#returns GE (geometry end and ground options)
# gnd   0 - free space, no ground
#       1 - ground and reflection
#      -1 - ground, without reflection
def GE_line (gnd):
    return f'GE {gnd} 0 0 0 0 0 0 0 0\n\n\n'
    


def write_CM(name, line):
    outfile=open(name, 'w')
    outfile.write('CM ---NEC file, automaticaly generated--- \nCM    by python script\n')
    line='CM '+line
    outfile.write(line)
    outfile.write('CE ---End of comments section--- \n\n\n')
    outfile.close()

def write_GW (name, tag, segs, start[], end[], diameter):
    radius=diameter/2
    outfile=open(name, 'a')
    GW_card=f'GW {tag:3} {segs:3} {start[0]:5} {start[1]:5} {start[2]:5} \
        {end[0]:5} {end[1]:5} {end[2]:5} {radius} \n'
    outfile.write(GW_card)
    outfile.close()

def write_GE (name, ground):
    outfile=open(name, 'a')
    GE_card=f'GE 0 0 0 0 0 0 0 0 0\n'
    outfile.write(GE_card)
    outfile.close()


    
